---
deployment:
  tasks:
    # Define the deployment path
    - export DEPLOYPATH=/home/housedes/public_html/housedesigns
    
    # Sync only changed files in the required directories
    - /bin/rsync -av --delete .next/ $DEPLOYPATH/.next
    - /bin/rsync -av --delete public/ $DEPLOYPATH/public
    
    # Sync individual files
    - /bin/rsync -av package.json package-lock.json $DEPLOYPATH/
    - /bin/rsync -av server.js $DEPLOYPATH/
    - /bin/rsync -av .env $DEPLOYPATH/
    
    # Create a deployment completion marker
    - /bin/touch $DEPLOYPATH/.deployment-completed