---
deployment:
  tasks:
    - export DEPLOYPATH=/home/housedes/public_html/housedesigns
    - /bin/cp -R .next $DEPLOYPATH/.next
    - /bin/cp -R public $DEPLOYPATH/public
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH/.env
    - echo "Deployment completed successfully!"