name: Deploy to cPanel

on:
  push:
    branches: [ main ]  # Deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Add environment configuration for better secret management
    environment: production
    
    # Define all environment variables once at the job level
    env:
      NODE_ENV: production
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      WC_CONSUMER_KEY: ${{ secrets.WC_CONSUMER_KEY }}
      WC_CONSUMER_SECRET: ${{ secrets.WC_CONSUMER_SECRET }}
    
    steps:
    # Step 1: Clone repository code
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Step 2: Setup Node.js environment - Node 18 LTS is recommended for Next.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.2'  # Using 18 LTS instead of 23.3.0 which is not yet stable
        cache: 'npm'  # Enables caching of npm dependencies
        
    # Step 3: Install project dependencies
    - name: Install dependencies
      run: npm install  # Use regular install instead of ci to avoid package-lock issues
      
    # Step 4: Build Next.js application with production settings
    - name: Build Next.js app
      run: npm run build
      # Environment variables are inherited from the job level, no need to repeat
      
    # Step 5: Deploy the .next directory (contains compiled application)
    - name: Deploy Next.js build files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./.next/  # Next.js build output
        server-dir: /public_html/housedesigns/.next/  # Update to include .next subfolder
        dangerous-clean-slate: false  # Changed to false to prevent deleting existing directories
        log-level: verbose
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules**
          
    # Step 6: Deploy necessary project files (excluding source and build artifacts)
    - name: Deploy supporting files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/housedesigns/  # This path seems correct
        log-level: verbose
        dangerous-clean-slate: false  # Change to false after first deployment: Cleans destination before uploading
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.next/**  # Exclude entire .next directory as it's already deployed
          **/src/**    # No need to deploy source files
          **/.github/**  # No need for GitHub files on production
          **/tests/**  # No need for test files on production
          **/*.log
          
          
    # Step 7: Restart PM2
    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Activate the virtual environment
          source /home/housedes/nodevenv/public_html/housedesigns/20/bin/activate
          
          # Navigate to the project directory
          cd /home/housedes/public_html/housedesigns
          
          # Ensure PM2 is installed
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found. Installing PM2..."
            npm install -g pm2
          fi
          
          # Reload or start the PM2 process
          if pm2 list | grep -q "housedesigns"; then
            echo "Reloading existing PM2 process..."
            pm2 reload housedesigns
          else
            echo "Starting new PM2 process..."
            pm2 start server.js --name housedesigns --update-env
          fi
          
          # Save PM2 process list to persist across server restarts
          pm2 save